import bungee_jumping as bj
import matplotlib.pyplot as plt

b1 = bj.BungeeJumping()
b1.init_cond(50,80,25,0,0.8,90)
t,y = b1.pomak(100)
plt.plot(t,y,label="Runge-Kutta")
plt.xlabel('t[s]')
plt.ylabel('y[m]')
plt.title('y-t graf')
plt.legend(loc="upper right")
plt.show()

Ek, Ep, Eel, E_uk = b1.doseg_energije()
plt.plot(t,Ek,label="kineticka energija", c = "black")
plt.plot(t,Ep,label="potencijalna energija", c = "green")
plt.plot(t,Eel,label="elasticna energija", c = "purple")
plt.plot(t,E_uk,label="ukupna energija", c = "blue")
plt.xlabel('t[s]')
plt.ylabel('E[J]')
plt.title('Sacuvanje energije, bez otpora')
plt.legend(loc="upper right")
plt.show()

b2 = bj.BungeeJumping()
b2.init_cond(50,80,25,1.,0.8,90)
t2,y2 = b2.pomak(100)
plt.plot(t2,y2,label="Runge-Kutta")
plt.xlabel('t[s]')
plt.ylabel('y[m]')
plt.title('y-t graf')
plt.legend(loc="upper right")
plt.show()

Ek2, Ep2, Eel2, E_uk2 = b2.doseg_energije()
plt.plot(t2,Ek2,label="kineticka energija", c = "black")
plt.plot(t2,Ep2,label="potencijalna energija", c = "green")
plt.plot(t2,Eel2,label="elasticna energija", c = "purple")
plt.plot(t2,E_uk2,label="ukupna energija", c = "blue")
plt.xlabel('t[s]')
plt.ylabel('E[J]')
plt.title('Sacuvanje energija, sa otporom')
plt.legend(loc="upper right")
plt.show()